name: Bicep

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep File
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./azure.bicep
        parameters: 'servicePrincipalObjectId=${{ vars.SERVICE_PRINCIPAL_ID }}'
        failOnStdErr: false
    
    - name: Add secrets to the Key vault
      uses: azure/cli@v2
      with:
        inlineScript: |
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "GithubAppID" --value "${{ secrets.APP_ID }}"
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "GithubInstallationID" --value "${{ secrets.APP_INSTALLATION_ID }}"
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "GithubAppPemFile" --value "${{ secrets.APP_PEM_FILE }}"
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "SupabaseEndpoint" --value "${{ secrets.SUPABASE_ENDPOINT }}"
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "SupabaseAPIKey" --value "${{ secrets.SUPABASE_API_KEY }}"
          az keyvault secret set --vault-name kv-app-minatsugo-bot --name "DiscordToken" --value "${{ secrets.DISCORD_TOKEN }}"
