name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    
    - name: Build
      run: go build -v cmd/main.go

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4 
      with:
        name: go-app 
        path: |
          .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: go-app
        path: .

    - name: Deploy
      uses: azure/webapps-deploy@v3
      id: deploy-to-azure
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}